#!/usr/bin/env bash
# Install nginx web server with the following requirements:
# Listen on port 80
# Return a page that contains the string "Holberton School" on requests
apt-get update
apt-get install -y nginx
echo "Holberton School" | tee /var/www/html/index.html
sed -i 's/root \/var\/www\/html;/root \/var\/www\/html;\n\trewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
service nginx restart
