#!/usr/bin/env bash
# Configure custom Nginx HTTP header
# shellcheck disable=SC2154
apt -y update
apt -y install nginx
sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | tee /usr/share/nginx/html/index.html
service nginx restart
