#!/usr/bin/env bash
# Create the file /var/run/holbertonscript.pid containing its PID
# Display To infinity and beyond indefinitely
# Display I hate the kill command when receiving a SIGTERM signal
# Display Y U no love me?! when receiving a SIGINT signal
# Delete the file /var/run/holbertonscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
      echo "To infinity and beyond"
      sleep 2
done
