#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=-1
while [ $((++hour)) -le 12 ]; do
	echo Hour: $hour
	minute=0
	while [ $((++minute)) -le 59 ]; do
		echo $minute
	done
done
